name: Add Assignee and Reviewer
on: pull_request_target

jobs:
  add-assignee-and-reviewer:
    runs-on: ubuntu-latest
    steps:
    # https://cli.github.com/manual/gh_pr_edit
    - name: Auto assign reviewer to PR
      if: endsWith(github.actor, '[bot]') == false && contains(github.event.action, 'opened')
      run: gh pr edit ${{ github.event.pull_request.html_url }} --add-assignee ${{ github.event.pull_request.user.login }} --add-reviewer remarkablemark
      env:
        GITHUB_TOKEN: ${{ github.token }}
