# https://commitlint.js.org/
name: commitlint
on:
  push:
  pull_request:
    # defaults to opened, synchronize, reopened
    types: [opened, synchronize, reopened, edited]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci

      - name: Lint commit message
        run: npx commitlint --from=HEAD~1

      - name: Lint PR title
        if: github.event_name == 'pull_request'
        run: |
          npx commitlint << EOF
          ${{ github.event.pull_request.title }}
          EOF

      - name: Lint string
        run: |
          echo 'chore: message' | npx commitlint

      # https://github.com/remarkablemark/commitlint
      - uses: remarkablemark/commitlint@v1
