name: commands
on: push

jobs:
  commands:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: cd
      shell: bash
      run: cd

    - name: echo
      shell: bash
      run: echo hello

    - name: find
      shell: bash
      run: find .

    - name: ls
      shell: bash
      run: ls

    - name: mv
      shell: bash
      run: |
        touch foo
        mv foo bar

    - name: sed
      shell: bash
      run: |
        echo hello > file.txt
        sed 's/h/j/' file.txt

    - name: source
      shell: bash
      run: |
        python -m venv .venv
        source $(find .venv -type f -name activate)

    - name: zip
      if: matrix.os != 'windows-latest'
      run: |
        touch file.txt
        zip archive.zip file.txt

    - name: zip
      if: matrix.os == 'windows-latest'
      # shell: powershell
      run: |
        touch file.txt
        Compress-Archive -Path file.txt -Destination archive.zip
