# https://docs.github.com/en/actions/learn-github-actions/contexts
name: GitHub Context
on: [push, pull_request]

jobs:
  github-context:
    runs-on: ubuntu-latest

    # https://www.edwardthomson.com/blog/github_actions_12_information_about_your_workflow.html
    steps:
      - name: github context
        run: echo '${{ toJson(github) }}'
        continue-on-error: true

      - name: job context
        run: echo '${{ toJson(job) }}'

      - name: steps context
        run: echo '${{ toJson(steps) }}'

      - name: runner context
        run: echo '${{ toJson(runner) }}'

      - name: strategy context
        run: echo '${{ toJson(strategy) }}'

      - name: matrix context
        run: echo '${{ toJson(matrix) }}'
