# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#adding-a-job-summary
name: Job summary
on: push

jobs:
  job-summary:
    runs-on: ubuntu-latest
    steps:
    - name: Example of adding a job summary
      run: echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY

    - name: Generate list using Markdown
      run: |
        echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
        echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
        echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
        echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY

    # - name: Overwrite Markdown
    #   run: |
    #     echo "Adding some Markdown content" >> $GITHUB_STEP_SUMMARY
    #     echo "There was an error, we need to clear the previous Markdown with some new content." > $GITHUB_STEP_SUMMARY

    # - name: Delete all summary content
    #   run: |
    #     echo "Adding Markdown content that we want to remove before the step ends" >> $GITHUB_STEP_SUMMARY
    #     rm $GITHUB_STEP_SUMMARY
