# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#multiline-strings
name: Multiline strings
on: push

jobs:
  multiline-strings:
    runs-on: ubuntu-latest
    steps:
      - name: Set the value
        run: |
          {
            echo 'JSON_RESPONSE<<EOF'
            curl https://example.com
            echo EOF
          } >> "$GITHUB_ENV"

      - name: Use the value
        run: printf '%s\n' "$JSON_RESPONSE"
