# https://github.com/marketplace/actions/repository-dispatch
name: Repository Dispatch
on: push
jobs:
  repository-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v4
        with:
          event-type: repository_dispatch_event
