name: Upload Artifact
on: push
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    # https://github.com/actions/upload-artifact#usage
    steps:
    - uses: actions/checkout@v3

    - run: mkdir -p path/to/artifact

    - run: echo hello > path/to/artifact/world.txt

    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: path/to/artifact/world.txt
