# https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello ${{ github.event.inputs.name }}!"
          echo "- in ${{ github.event.inputs.home }}!"

      - if: github.event.inputs.name == 'Mona'
        run: echo "Name is Mona"

      - if: github.event.inputs.name != 'Mona'
        run: echo "Name is not Mona"

      - if: contains(github.event.inputs.name, 'Mona')
        run: echo "Name contains Mona"

      - if: contains(github.event.inputs.name, 'Mona') == false
        run: echo "Name does not contain Mona"

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
# on:
#   workflow_dispatch:
#     inputs:
#       logLevel:
#         description: 'Log level'
#         required: true
#         default: 'warning'
#         type: choice
#         options:
#         - info
#         - warning
#         - debug
#       tags:
#         description: 'Test scenario tags'
#         required: false
#         type: boolean
#       environment:
#         description: 'Environment to run tests against'
#         type: environment
#         required: true
# 
# jobs:
#   log-the-inputs:
#     runs-on: ubuntu-latest
#     steps:
#       - run: |
#           echo "Log level: $LEVEL"
#           echo "Tags: $TAGS"
#           echo "Environment: $ENVIRONMENT"
#         env:
#           LEVEL: ${{ inputs.logLevel }}
#           TAGS: ${{ inputs.tags }}
#           ENVIRONMENT: ${{ inputs.environment }}
